engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - 5a32d66f61ea18f2f75921056fc89593
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.rake"
exclude_paths:
- .binstubs/
- .bundle/
- .gems/
- .git/
- bin/
- coverage/
- pkg/
- spec/
