sudo: false
language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.12.5
install: ./bin/setup

addons:
    code_climate:
        repo_token: 488c417d6ba946ef7cea3101be8bbd46f2bf6092c52f8907d321c63b69c69085
