sudo: false
language: ruby
rvm:
  - 2.4.2

env:
  global:
    - CC_TEST_REPORTER_ID=488c417d6ba946ef7cea3101be8bbd46f2bf6092c52f8907d321c63b69c69085

before_install: gem install bundler -v 1.16.0
install: ./bin/setup

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

